name: CI

on: [push, workflow_dispatch]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - run: |
          OUTPUT="$(jq --arg nodeVersion ${{ matrix.node-version }} '.engines.node = $nodeVersion' package.json)"
          echo "$OUTPUT" > package.json

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml

      - run: pnpm i && pnpm check
        name: Lint and Test
